### ISSUE TITLE
🔒 i3lock & betterlockscreen support

### ISSUE THREAD

**Issue by FelipeFTN** [jluttine/rofi-power-menu#27]
I'm basically reopening this issue here #21 since I'm having the exact same problem. Can you please help me to solve it?
<div align="center">

![image](https://github.com/jluttine/rofi-power-menu/assets/80127749/4bbb1de3-bb24-4a45-b4e6-f055c39f1bd4)

</div>

After applying those changes to the script, I get a error from i3lock, warning that locking wasn't possible, then it stops the screen locking. So strange behavior, isn't it? Anyone can help me?
I'm using i3lock-color because I want to blur my desktop during my screenlock.
Executing the same command on the terminal, works just fine!

```bash
   $ i3lock --nofork --color=00000000
```

**Comment by Daniel-McLarty** [comment]
Me too, it wont work with it for some reason.

**Comment by KaXMaXimum** [comment]
The problem is that rofi holds a lock on the keyboard and i3lock is therefore unable to have access to the keyboard and instead quits (probably so that you don't get stuck on the lockscreen without a functioning keyboard)

A solution is to kill rofi before executing the chosen action. This can be done by adding the the following line to line 266 of the script
`...`
				`# kill rofi (this line needs to be added)`
				`killall rofi`
                `# Perform the action (this was already in the script)`
                `${actions[$entry]}`
`...`

**Comment by FelipeFTN** [comment]
**Wooow, thank you so much @KaXMaXimum!**
Your solution worked just fine!! :rocket: 

I think this solves the issue I was having! :100: 

![image](https://github.com/jluttine/rofi-power-menu/assets/80127749/cef17bab-0969-4314-b7ee-87fb063c8a34)
